### ISSUE TITLE
identificator "json_value_pair" isn't defined

### ISSUE THREAD

**Issue by pavelc7** [sciter-sdk/json-value-visualizer#3]
what is json_value_pair ?
Natvis: ...\2019\Professional\Common7\Packages\Debugger\Visualizers\sciter.natvis(87,27): Error: identificator "json_value_pair" isn't defined
    Error in evaluation of "((json_value_pair*)( ((int*)d) + 3 ))" in context of "MyProgram.exe!sciter::value".

**Comment by pavelc7** [comment]
don't not why it's start working after adding to my sources:
```
using json_value_pair = std::pair<sciter::value, sciter::value>;

void my_func(){
...
json_value_pair x;
...
code with map using
}
```

**Comment by pravic** [comment]
It's mentioned in the readme.

The map data structure in sciter is essentially an array of key-value pairs (not tree or something). In order to display the contents of a map I need some type that looks like a pair. And json_value_pair is a promise that this type will be available in debugger. I don't have a better idea.

**Comment by pavelc7** [comment]
Oops. Sorry. I read readme before installing it;)
